# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JMatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JMatch
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'JSQMessagesViewController'
  pod 'MBProgressHUD', '~> 1.1.0'
end
